apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: author-marketplace
  name: author-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-marketplace
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: author-marketplace
    spec:
      containers:
        - image: IMAGE:TAG
          name: author-marketplace
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "150m"
status: {}
