apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: author-marketplace
  labels:
    name: author-marketplace
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: author-marketplace
                port:
                  number: 80